---
- name: reload systemd daemon
  become: true
  systemd:
    daemon_reload: true

- name: reload udev rules
  become: true
  command: udevadm control --reload-rules
  changed_when: true

- name: restart networkmanager
  become: true
  systemd:
    name: NetworkManager.service
    state: restarted

- name: restart lightdm
  become: true
  systemd:
    name: lightdm
    state: restarted

- name: update grub
  become: true
  command: update-grub

- name: rebuild console font
  become: true
  command: dpkg-reconfigure -f noninteractive console-setup
